---
title: "-- Day 10 --"
format: gfm
editor: visual
---

```{r, message = FALSE}
library(tidyverse)
```

## Part 1 - Function

```{r}

build_stack <- function(file) {

  read_fwf(file = file, 
    col_positions = fwf_widths(widths = c(4, 4),
     col_names = c("op", "x")), 
    show_col_types = "spec") %>%

  mutate(
    curr_cycles = if_else(op == "addx", 2, 1), # number of current cycles
    CYCLE = cumsum(curr_cycles), # completed cycles at end of current cycles, 
    x = if_else(is.na(x), 0, x), # addition to x at end of current cycles
    X = 1 + cumsum(x) # X at the end of the current cycle
  )
}


```

## Part 1 - Example

```{r}
# Need value of X DURING CYCLE 20, 40, 100, etc.
# which is the value of X at the end of the prior CYCLE

stack <- build_stack("data/input10a_test.txt")

map_dfr(seq(20, 220, 40), ~ stack %>% 
# took me a while to realize during implies < not <=
  filter(CYCLE == max(stack$CYCLE[stack$CYCLE < .x])) %>% 
  mutate(SS = .x * X)) %>%

pull(SS) %>% sum()


```

## Part 1 - Solution

```{r}
stack <- build_stack("data/input10a.txt")
max(stack$CYCLE)

map_dfr(seq(20, 220, 40), ~ stack %>% 
  filter(CYCLE == max(stack$CYCLE[stack$CYCLE < .x])) %>% 
  mutate(SS = .x * X)) %>%  # SS = signal strength
  
  pull(SS) %>% sum()

```

## Part 2 -- Function

```{r}

build_stack2 <- function(file) {

  stack <-  
  read_fwf(file = file, 
    col_positions = fwf_widths(widths = c(4, 4),
     col_names = c("op", "x")), 
    show_col_types = "spec") %>%
 
  mutate(
    op_cycles = if_else(op == "addx", 2, 1), # number of current cycles
    x = if_else(is.na(x), 0, x), # addition to x at end of current cycles
    X = 1 + cumsum(x) - x # X at BEGINNING of the current cycle
    )
 
  # expand data frame so there is one row per cycle
  map_dfr(stack, rep, stack$op_cycles) %>% 
    mutate(
      px_pos = 0:(n()-1), # cycle - 1 using below with %% 40
      sprt_l = X-1,
      sprt_r = X+1,
      lit = if_else((px_pos %% 40) >= sprt_l & (px_pos %% 40) <= sprt_r, "#", ".")
    ) %>%
    select(px_pos, x, X, sprt_l, sprt_r, lit) 
  
}


```

## Part 2 - Example

```{r}
stack2 <- build_stack2("data/input10a_test.txt")

for(i in 0:5) {
print(paste0(stack2$lit[(i*40 + 1):(i*40 + 40)], collapse = ""))
}

```

## Part 2 - Solution

```{r}
stack2 <- build_stack2("data/input10a.txt")

for(i in 0:5) {
print(paste0(stack2$lit[(i*40 + 1):(i*40 + 40)], collapse = ""))
}
"BGKAEREZ"
```
